package krm.gui;

import krm.gui.handler.FileCompressHandler;
import krm.gui.handler.FileExpanderHandler;
import krm.gui.handler.FileDropHandler;

import javax.swing.*;
import javax.swing.border.TitledBorder;
import java.awt.*;

public class MainView extends JFrame {
    private JPanel contentPanel;
    private JLabel warningLabel;

    private JPanel pathPanel;
    private JTextField pathFileField;

    private JPanel compressPanel;
    private JButton compressButton;
    private JButton reestablishButton;

    private JScrollPane scrollPanel;
    private JTextArea textArea;

    public MainView() throws HeadlessException {
        setContentPane(contentPanel);
        setTitle("press for files");
        setLocationRelativeTo(null);
        pack();
        setDefaultCloseOperation(WindowConstants.EXIT_ON_CLOSE);
        setVisible(true);

        // drop file
        pathFileField.setTransferHandler(new FileDropHandler(pathFileField, warningLabel));

        compressButton.addActionListener(new FileCompressHandler(pathFileField, warningLabel, textArea));
        reestablishButton.addActionListener(new FileExpanderHandler(pathFileField, warningLabel));
    }

    public static void main(String[] args) {
        MainView viewApp = new MainView();
    }


    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        contentPanel = new JPanel();
        contentPanel.setLayout(new FlowLayout(FlowLayout.CENTER, 2, 2));
        contentPanel.setAlignmentX(0.0f);
        contentPanel.setAlignmentY(0.0f);
        contentPanel.setAutoscrolls(true);
        contentPanel.setBackground(new Color(-12148993));
        contentPanel.setDoubleBuffered(true);
        contentPanel.setEnabled(false);
        contentPanel.setFocusCycleRoot(false);
        contentPanel.setFocusTraversalPolicyProvider(false);
        contentPanel.setFocusable(true);
        contentPanel.setMaximumSize(new Dimension(500, 500));
        contentPanel.setMinimumSize(new Dimension(400, 108));
        contentPanel.setName("press for files");
        contentPanel.setOpaque(true);
        contentPanel.setPreferredSize(new Dimension(405, 415));
        warningLabel = new JLabel();
        warningLabel.setAlignmentX(0.0f);
        warningLabel.setAlignmentY(0.0f);
        warningLabel.setAutoscrolls(false);
        warningLabel.setBackground(new Color(-4213966));
        warningLabel.setDebugGraphicsOptions(1);
        warningLabel.setDoubleBuffered(true);
        warningLabel.setEnabled(true);
        warningLabel.setFocusCycleRoot(false);
        warningLabel.setForeground(new Color(-1828583));
        warningLabel.setHorizontalAlignment(0);
        warningLabel.setHorizontalTextPosition(4);
        warningLabel.setInheritsPopupMenu(true);
        warningLabel.setMaximumSize(new Dimension(400, 20));
        warningLabel.setMinimumSize(new Dimension(400, 5));
        warningLabel.setOpaque(true);
        warningLabel.setPreferredSize(new Dimension(400, 20));
        warningLabel.setRequestFocusEnabled(true);
        warningLabel.setText("передайте файл в поле ввода");
        contentPanel.add(warningLabel);
        pathPanel = new JPanel();
        pathPanel.setLayout(new GridBagLayout());
        pathPanel.setAlignmentX(0.0f);
        pathPanel.setAlignmentY(0.0f);
        pathPanel.setBackground(new Color(-10437745));
        pathPanel.setMaximumSize(new Dimension(400, 100));
        pathPanel.setMinimumSize(new Dimension(400, 45));
        pathPanel.setName("");
        pathPanel.setOpaque(true);
        pathPanel.setPreferredSize(new Dimension(400, 45));
        pathPanel.setRequestFocusEnabled(true);
        pathPanel.setToolTipText("");
        contentPanel.add(pathPanel);
        pathPanel.setBorder(BorderFactory.createTitledBorder(BorderFactory.createEmptyBorder(0, 0, 0, 0), "path", TitledBorder.LEFT, TitledBorder.TOP, new Font(pathPanel.getFont().getName(), pathPanel.getFont().getStyle(), pathPanel.getFont().getSize()), new Color(-1)));
        pathFileField = new JTextField();
        pathFileField.setAlignmentX(0.0f);
        pathFileField.setAlignmentY(0.0f);
        pathFileField.setColumns(0);
        pathFileField.setDoubleBuffered(false);
        pathFileField.setDragEnabled(false);
        pathFileField.setDropMode(DropMode.USE_SELECTION);
        pathFileField.setEditable(true);
        pathFileField.setEnabled(true);
        pathFileField.setMaximumSize(new Dimension(400, 30));
        pathFileField.setMinimumSize(new Dimension(400, 20));
        pathFileField.setOpaque(true);
        pathFileField.setPreferredSize(new Dimension(400, 25));
        pathFileField.setRequestFocusEnabled(true);
        pathFileField.setText("");
        pathFileField.putClientProperty("html.disable", Boolean.FALSE);
        GridBagConstraints gbc;
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 0;
        gbc.weightx = 1.0;
        pathPanel.add(pathFileField, gbc);
        compressPanel = new JPanel();
        compressPanel.setLayout(new BorderLayout(0, 0));
        compressPanel.setAlignmentX(0.0f);
        compressPanel.setAlignmentY(0.0f);
        compressPanel.setAutoscrolls(false);
        compressPanel.setBackground(new Color(-10437745));
        compressPanel.setDoubleBuffered(true);
        compressPanel.setFocusCycleRoot(false);
        compressPanel.setFocusTraversalPolicyProvider(false);
        compressPanel.setMaximumSize(new Dimension(400, 40));
        compressPanel.setMinimumSize(new Dimension(50, 20));
        compressPanel.setOpaque(true);
        compressPanel.setPreferredSize(new Dimension(400, 35));
        compressPanel.setRequestFocusEnabled(false);
        compressPanel.putClientProperty("html.disable", Boolean.TRUE);
        contentPanel.add(compressPanel);
        compressPanel.setBorder(BorderFactory.createTitledBorder(BorderFactory.createEmptyBorder(0, 0, 0, 0), null, TitledBorder.DEFAULT_JUSTIFICATION, TitledBorder.DEFAULT_POSITION, new Font(compressPanel.getFont().getName(), compressPanel.getFont().getStyle(), compressPanel.getFont().getSize())));
        compressButton = new JButton();
        compressButton.setAlignmentY(0.0f);
        compressButton.setBorderPainted(true);
        compressButton.setDoubleBuffered(false);
        compressButton.setEnabled(true);
        compressButton.setFocusCycleRoot(false);
        compressButton.setFocusPainted(true);
        compressButton.setFocusTraversalPolicyProvider(false);
        compressButton.setFocusable(true);
        compressButton.setHideActionText(false);
        compressButton.setHorizontalTextPosition(0);
        compressButton.setMargin(new Insets(2, 2, 2, 2));
        compressButton.setMaximumSize(new Dimension(95, 36));
        compressButton.setMinimumSize(new Dimension(95, 36));
        compressButton.setOpaque(false);
        compressButton.setPreferredSize(new Dimension(95, 36));
        compressButton.setRolloverEnabled(false);
        compressButton.setSelected(false);
        compressButton.setText("compress");
        compressButton.setVerifyInputWhenFocusTarget(true);
        compressButton.setVisible(true);
        compressPanel.add(compressButton, BorderLayout.WEST);
        reestablishButton = new JButton();
        reestablishButton.setAlignmentY(0.0f);
        reestablishButton.setAutoscrolls(false);
        reestablishButton.setDoubleBuffered(false);
        reestablishButton.setEnabled(true);
        reestablishButton.setFocusCycleRoot(false);
        reestablishButton.setFocusPainted(true);
        reestablishButton.setFocusTraversalPolicyProvider(false);
        reestablishButton.setFocusable(true);
        reestablishButton.setHideActionText(false);
        reestablishButton.setHorizontalTextPosition(0);
        reestablishButton.setMargin(new Insets(2, 2, 2, 2));
        reestablishButton.setMaximumSize(new Dimension(95, 36));
        reestablishButton.setMinimumSize(new Dimension(95, 36));
        reestablishButton.setOpaque(false);
        reestablishButton.setPreferredSize(new Dimension(95, 36));
        reestablishButton.setRolloverEnabled(false);
        reestablishButton.setSelected(false);
        reestablishButton.setText("reestablish");
        reestablishButton.setVerifyInputWhenFocusTarget(true);
        reestablishButton.setVisible(true);
        compressPanel.add(reestablishButton, BorderLayout.EAST);
        scrollPanel = new JScrollPane();
        scrollPanel.setOpaque(false);
        scrollPanel.setPreferredSize(new Dimension(400, 300));
        scrollPanel.setRequestFocusEnabled(false);
        contentPanel.add(scrollPanel);
        textArea = new JTextArea();
        textArea.setEditable(false);
        textArea.setEnabled(true);
        textArea.setText("");
        scrollPanel.setViewportView(textArea);
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return contentPanel;
    }
}
