package krm.gui;

import krm.gui.handler.CompressFileHandler;
import krm.gui.handler.ExpanderFileHandler;
import krm.gui.handler.FileDropHandler;

import javax.swing.*;
import javax.swing.border.TitledBorder;
import java.awt.*;

public class MainViewApp extends JFrame {
    private JPanel contentPane;
    private JTextField pathFileField;
    private JPanel pathPanel;
    private JLabel messagesLabel;

    private JButton compressButton;
    private JButton reestablishButton;
    private JPanel compressPanel;

    public MainViewApp() throws HeadlessException {
        setContentPane(contentPane);
        setTitle("press for files");
        setLocationRelativeTo(null);
        pack();
        setDefaultCloseOperation(WindowConstants.EXIT_ON_CLOSE);
        setVisible(true);

        // drop file
        pathFileField.setTransferHandler(new FileDropHandler(pathFileField, messagesLabel));

        compressButton.addActionListener(new CompressFileHandler(pathFileField, messagesLabel));
        reestablishButton.addActionListener(new ExpanderFileHandler(pathFileField, messagesLabel));
    }

    public static void main(String[] args) {
        MainViewApp viewApp = new MainViewApp();
    }

    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        contentPane = new JPanel();
        contentPane.setLayout(new FlowLayout(FlowLayout.CENTER, 2, 2));
        contentPane.setAlignmentX(0.0f);
        contentPane.setAlignmentY(0.0f);
        contentPane.setAutoscrolls(true);
        contentPane.setBackground(new Color(-12148993));
        contentPane.setDoubleBuffered(true);
        contentPane.setEnabled(false);
        contentPane.setFocusCycleRoot(false);
        contentPane.setFocusTraversalPolicyProvider(false);
        contentPane.setFocusable(true);
        contentPane.setMaximumSize(new Dimension(500, 500));
        contentPane.setMinimumSize(new Dimension(400, 108));
        contentPane.setName("press for files");
        contentPane.setOpaque(true);
        contentPane.setPreferredSize(new Dimension(405, 108));
        messagesLabel = new JLabel();
        messagesLabel.setAlignmentX(0.0f);
        messagesLabel.setAlignmentY(0.0f);
        messagesLabel.setAutoscrolls(false);
        messagesLabel.setBackground(new Color(-4213966));
        messagesLabel.setDebugGraphicsOptions(1);
        messagesLabel.setDoubleBuffered(true);
        messagesLabel.setEnabled(true);
        messagesLabel.setFocusCycleRoot(false);
        messagesLabel.setForeground(new Color(-1828583));
        messagesLabel.setHorizontalAlignment(0);
        messagesLabel.setHorizontalTextPosition(4);
        messagesLabel.setInheritsPopupMenu(true);
        messagesLabel.setMaximumSize(new Dimension(400, 20));
        messagesLabel.setMinimumSize(new Dimension(400, 5));
        messagesLabel.setOpaque(true);
        messagesLabel.setPreferredSize(new Dimension(400, 20));
        messagesLabel.setRequestFocusEnabled(true);
        messagesLabel.setText("передайте файл в поле ввода");
        contentPane.add(messagesLabel);
        pathPanel = new JPanel();
        pathPanel.setLayout(new GridBagLayout());
        pathPanel.setAlignmentX(0.0f);
        pathPanel.setAlignmentY(0.0f);
        pathPanel.setBackground(new Color(-10437745));
        pathPanel.setMaximumSize(new Dimension(400, 100));
        pathPanel.setMinimumSize(new Dimension(400, 45));
        pathPanel.setName("");
        pathPanel.setOpaque(true);
        pathPanel.setPreferredSize(new Dimension(400, 45));
        pathPanel.setRequestFocusEnabled(true);
        pathPanel.setToolTipText("");
        contentPane.add(pathPanel);
        pathPanel.setBorder(BorderFactory.createTitledBorder(BorderFactory.createEmptyBorder(0, 0, 0, 0), "path", TitledBorder.LEFT, TitledBorder.TOP, new Font(pathPanel.getFont().getName(), pathPanel.getFont().getStyle(), pathPanel.getFont().getSize()), new Color(-1)));
        pathFileField = new JTextField();
        pathFileField.setAlignmentX(0.0f);
        pathFileField.setAlignmentY(0.0f);
        pathFileField.setColumns(0);
        pathFileField.setDoubleBuffered(false);
        pathFileField.setDragEnabled(false);
        pathFileField.setDropMode(DropMode.USE_SELECTION);
        pathFileField.setEditable(true);
        pathFileField.setEnabled(true);
        pathFileField.setMaximumSize(new Dimension(400, 30));
        pathFileField.setMinimumSize(new Dimension(400, 20));
        pathFileField.setOpaque(true);
        pathFileField.setPreferredSize(new Dimension(400, 25));
        pathFileField.setRequestFocusEnabled(true);
        pathFileField.setText("");
        pathFileField.putClientProperty("html.disable", Boolean.FALSE);
        GridBagConstraints gbc;
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 0;
        gbc.weightx = 1.0;
        pathPanel.add(pathFileField, gbc);
        compressPanel = new JPanel();
        compressPanel.setLayout(new BorderLayout(0, 0));
        compressPanel.setAlignmentX(0.0f);
        compressPanel.setAlignmentY(0.0f);
        compressPanel.setAutoscrolls(false);
        compressPanel.setBackground(new Color(-10437745));
        compressPanel.setDoubleBuffered(true);
        compressPanel.setFocusCycleRoot(false);
        compressPanel.setFocusTraversalPolicyProvider(false);
        compressPanel.setMaximumSize(new Dimension(400, 40));
        compressPanel.setMinimumSize(new Dimension(50, 20));
        compressPanel.setOpaque(true);
        compressPanel.setPreferredSize(new Dimension(400, 35));
        compressPanel.setRequestFocusEnabled(false);
        compressPanel.putClientProperty("html.disable", Boolean.TRUE);
        contentPane.add(compressPanel);
        compressPanel.setBorder(BorderFactory.createTitledBorder(BorderFactory.createEmptyBorder(0, 0, 0, 0), null, TitledBorder.DEFAULT_JUSTIFICATION, TitledBorder.DEFAULT_POSITION, new Font(compressPanel.getFont().getName(), compressPanel.getFont().getStyle(), compressPanel.getFont().getSize())));
        compressButton = new JButton();
        compressButton.setAlignmentY(0.0f);
        compressButton.setBorderPainted(true);
        compressButton.setDoubleBuffered(false);
        compressButton.setEnabled(true);
        compressButton.setFocusCycleRoot(false);
        compressButton.setFocusPainted(true);
        compressButton.setFocusTraversalPolicyProvider(false);
        compressButton.setFocusable(true);
        compressButton.setHideActionText(false);
        compressButton.setHorizontalTextPosition(0);
        compressButton.setMargin(new Insets(2, 2, 2, 2));
        compressButton.setMaximumSize(new Dimension(95, 36));
        compressButton.setMinimumSize(new Dimension(95, 36));
        compressButton.setOpaque(false);
        compressButton.setPreferredSize(new Dimension(95, 36));
        compressButton.setRolloverEnabled(false);
        compressButton.setSelected(false);
        compressButton.setText("compress");
        compressButton.setVerifyInputWhenFocusTarget(true);
        compressButton.setVisible(true);
        compressPanel.add(compressButton, BorderLayout.WEST);
        reestablishButton = new JButton();
        reestablishButton.setAlignmentY(0.0f);
        reestablishButton.setAutoscrolls(false);
        reestablishButton.setDoubleBuffered(false);
        reestablishButton.setEnabled(true);
        reestablishButton.setFocusCycleRoot(false);
        reestablishButton.setFocusPainted(true);
        reestablishButton.setFocusTraversalPolicyProvider(false);
        reestablishButton.setFocusable(true);
        reestablishButton.setHideActionText(false);
        reestablishButton.setHorizontalTextPosition(0);
        reestablishButton.setMargin(new Insets(2, 2, 2, 2));
        reestablishButton.setMaximumSize(new Dimension(95, 36));
        reestablishButton.setMinimumSize(new Dimension(95, 36));
        reestablishButton.setOpaque(false);
        reestablishButton.setPreferredSize(new Dimension(95, 36));
        reestablishButton.setRolloverEnabled(false);
        reestablishButton.setSelected(false);
        reestablishButton.setText("reestablish");
        reestablishButton.setVerifyInputWhenFocusTarget(true);
        reestablishButton.setVisible(true);
        compressPanel.add(reestablishButton, BorderLayout.EAST);
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return contentPane;
    }
}
