package krm.gui;

import javax.swing.*;
import javax.swing.border.TitledBorder;
import java.awt.*;


public class ViewApp extends JFrame {
    private JPanel contentPane;
    private JTextField pathFileField;
    private JPanel pathPanel;
    private JLabel messagesLabel;
    private JPanel bottomPanel;
    private JButton compressButton;
    private JButton reestablishButton;

    public ViewApp() throws HeadlessException {
        setContentPane(contentPane);
        setTitle("press for files");
        pack();
        setDefaultCloseOperation(WindowConstants.EXIT_ON_CLOSE);
        setVisible(true);

        pathFileField.setTransferHandler(new FileDropHandler(pathFileField, messagesLabel));
    }

    public static void main(String[] args) {
        ViewApp viewApp = new ViewApp();
    }

    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        contentPane = new JPanel();
        contentPane.setLayout(new GridBagLayout());
        contentPane.setAlignmentX(0.0f);
        contentPane.setAlignmentY(0.0f);
        contentPane.setAutoscrolls(false);
        contentPane.setBackground(new Color(-12148993));
        contentPane.setDoubleBuffered(true);
        contentPane.setEnabled(true);
        contentPane.setFocusCycleRoot(false);
        contentPane.setFocusTraversalPolicyProvider(false);
        contentPane.setFocusable(true);
        contentPane.setMaximumSize(new Dimension(500, 500));
        contentPane.setMinimumSize(new Dimension(405, 130));
        contentPane.setName("press for files");
        contentPane.setOpaque(true);
        contentPane.setPreferredSize(new Dimension(405, 130));
        contentPane.setBorder(BorderFactory.createTitledBorder(BorderFactory.createEmptyBorder(0, 0, 0, 0), null, TitledBorder.DEFAULT_JUSTIFICATION, TitledBorder.DEFAULT_POSITION, new Font(contentPane.getFont().getName(), contentPane.getFont().getStyle(), contentPane.getFont().getSize())));
        bottomPanel = new JPanel();
        bottomPanel.setLayout(new GridBagLayout());
        bottomPanel.setAlignmentX(0.0f);
        bottomPanel.setAlignmentY(0.0f);
        bottomPanel.setAutoscrolls(false);
        bottomPanel.setBackground(new Color(-10437745));
        bottomPanel.setFocusCycleRoot(false);
        bottomPanel.setFocusTraversalPolicyProvider(false);
        bottomPanel.setMaximumSize(new Dimension(400, 80));
        bottomPanel.setMinimumSize(new Dimension(400, 40));
        bottomPanel.setPreferredSize(new Dimension(400, 40));
        bottomPanel.setRequestFocusEnabled(false);
        bottomPanel.putClientProperty("html.disable", Boolean.TRUE);
        GridBagConstraints gbc;
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 2;
        gbc.insets = new Insets(2, 2, 2, 2);
        contentPane.add(bottomPanel, gbc);
        bottomPanel.setBorder(BorderFactory.createTitledBorder(BorderFactory.createEmptyBorder(0, 0, 0, 0), null, TitledBorder.DEFAULT_JUSTIFICATION, TitledBorder.DEFAULT_POSITION, new Font(bottomPanel.getFont().getName(), bottomPanel.getFont().getStyle(), bottomPanel.getFont().getSize())));
        reestablishButton = new JButton();
        reestablishButton.setAlignmentY(0.0f);
        reestablishButton.setHorizontalTextPosition(0);
        reestablishButton.setMargin(new Insets(2, 2, 2, 2));
        reestablishButton.setSelected(false);
        reestablishButton.setText("reestablish");
        reestablishButton.setVisible(true);
        gbc = new GridBagConstraints();
        gbc.gridx = 1;
        gbc.gridy = 0;
        gbc.anchor = GridBagConstraints.EAST;
        bottomPanel.add(reestablishButton, gbc);
        compressButton = new JButton();
        compressButton.setAlignmentY(0.0f);
        compressButton.setHorizontalTextPosition(0);
        compressButton.setMargin(new Insets(2, 2, 2, 2));
        compressButton.setSelected(false);
        compressButton.setText("compress");
        compressButton.setVisible(true);
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 0;
        gbc.anchor = GridBagConstraints.WEST;
        bottomPanel.add(compressButton, gbc);
        messagesLabel = new JLabel();
        messagesLabel.setAlignmentX(0.0f);
        messagesLabel.setAlignmentY(0.0f);
        messagesLabel.setAutoscrolls(false);
        messagesLabel.setBackground(new Color(-4842));
        messagesLabel.setDebugGraphicsOptions(1);
        messagesLabel.setDoubleBuffered(false);
        messagesLabel.setEnabled(true);
        messagesLabel.setFocusCycleRoot(false);
        messagesLabel.setForeground(new Color(-1828583));
        messagesLabel.setHorizontalTextPosition(4);
        messagesLabel.setInheritsPopupMenu(true);
        messagesLabel.setMaximumSize(new Dimension(400, 20));
        messagesLabel.setMinimumSize(new Dimension(400, 5));
        messagesLabel.setOpaque(true);
        messagesLabel.setPreferredSize(new Dimension(400, 20));
        messagesLabel.setRequestFocusEnabled(true);
        messagesLabel.setText("*");
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 1;
        gbc.fill = GridBagConstraints.BOTH;
        gbc.insets = new Insets(0, 2, 0, 2);
        contentPane.add(messagesLabel, gbc);
        pathPanel = new JPanel();
        pathPanel.setLayout(new GridBagLayout());
        pathPanel.setAlignmentX(0.0f);
        pathPanel.setAlignmentY(0.0f);
        pathPanel.setBackground(new Color(-10437745));
        pathPanel.setMaximumSize(new Dimension(400, 100));
        pathPanel.setMinimumSize(new Dimension(400, 50));
        pathPanel.setName("");
        pathPanel.setPreferredSize(new Dimension(400, 50));
        pathPanel.setRequestFocusEnabled(true);
        pathPanel.setToolTipText("");
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 0;
        gbc.fill = GridBagConstraints.BOTH;
        gbc.insets = new Insets(2, 2, 2, 2);
        contentPane.add(pathPanel, gbc);
        pathPanel.setBorder(BorderFactory.createTitledBorder(BorderFactory.createEmptyBorder(0, 0, 0, 0), "path", TitledBorder.LEFT, TitledBorder.TOP, new Font(pathPanel.getFont().getName(), pathPanel.getFont().getStyle(), pathPanel.getFont().getSize())));
        pathFileField = new JTextField();
        pathFileField.setDragEnabled(false);
        pathFileField.setDropMode(DropMode.USE_SELECTION);
        pathFileField.setEditable(true);
        pathFileField.setEnabled(true);
        pathFileField.setOpaque(true);
        pathFileField.setText("");
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 0;
        gbc.weightx = 1.0;
        gbc.anchor = GridBagConstraints.WEST;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        pathPanel.add(pathFileField, gbc);
        messagesLabel.setLabelFor(pathFileField);
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return contentPane;
    }
}
